#!/usr/bin/env python3
"""Enhance remaining /tools pages (batches 2-5). Uses enhance() from _enhance_tools."""
import sys, os
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from _enhance_tools import enhance

def T(slug,name,steps,fqs,rel,meta=None):
    return dict(slug=slug,name=name,steps=steps,faqs_custom=fqs,related=rel,new_meta=meta)

REST=[
 T("content-recency-decay","Content Recency Decay Estimator",
  ["Enter the page's topic type and last-updated date.","See the modeled citation decay curve per engine.","Set a refresh cadence before the half-life passes."],
  [("How fast do AI citations decay?","It varies by engine and topic, but pages left un-updated lose citation share measurably within a quarter, faster on recency-sensitive engines like Perplexity and Google's AI surfaces. The estimator models the curve so you refresh before the drop, not after."),
   ("How often should I refresh a page?","Refresh on a cadence tied to the topic's volatility: fast-moving categories every 4-8 weeks, evergreen ones quarterly. Update the substance and the dateModified in schema, a date change alone does not reset the clock.")],
  [("Content freshness: the 30-day AI half-life","/blogs/30-day-content-half-life-recency-ai-ranking-signal"),("Prompt-to-citation tracking","/blogs/prompt-to-citation-tracking"),("GEO Readiness Scorecard","/tools/geo-readiness-scorecard")]),
 T("crawl-depth-retrieval-estimator","Crawl-Depth Retrieval Estimator",
  ["Enter a page's click-depth from your homepage.","See the modeled odds a real-time AI agent reaches it in time.","Flatten deep pages toward a 2-3 click depth."],
  [("Why does crawl depth matter for AI retrieval?","Real-time citation agents fetch under a hard timeout. Pages buried many clicks from the homepage are reached late or not at all, so they never enter the candidate pool, however good they are. A flat 2-3 hop depth keeps your key pages reachable."),
   ("How do I reduce a page's crawl depth?","Link to it from your homepage, hub pages and topic clusters, and keep the internal-link graph shallow. Every hop you remove raises the odds a time-boxed agent reaches the page before it gives up.")],
  [("Internal linking for AI retrieval","/blogs/internal-linking-for-ai-retrieval"),("How AI crawlers index your site","/blogs/how-ai-crawlers-index-your-site"),("Retrieval-Readiness Checklist","/tools/retrieval-readiness-checklist")]),
 T("cross-engine-source-overlap-calculator","Cross-Engine Source Overlap Calculator",
  ["Paste the domains each engine cited for one prompt.","Read the pairwise Jaccard overlap scores.","Target the distinct domains each engine favours."],
  [("What is a normal cross-engine source overlap?","Low. For the same prompt, engines typically share only 16 to 20 percent of cited domains, because each runs a different index and re-ranker. Overlap above 0.35 usually means your prompt set is too narrow to generalise."),
   ("What do I do with a low overlap score?","Treat each engine as a separate off-page target. The domains ChatGPT cites are not the ones Perplexity cites, so a single link-building or PR list will not cover them. The matrix shows which domains to pursue for which engine.")],
  [("Why engines recommend different vendors","/blogs/why-engines-recommend-different-vendors"),("Citation vs Mention vs Recommendation","/blogs/citation-vs-mention-vs-recommendation"),("Platform-Weighted Visibility Calculator","/tools/platform-weighted-visibility-calculator")]),
 T("dual-track-visibility-scorecard","Dual-Track AI Visibility Scorecard",
  ["Score the AI Overviews track and the AI Mode track separately.","See which gaps are unique to each surface.","Fix the track with the weaker score first."],
  [("Why score AI Overviews and AI Mode separately?","Google's two AI surfaces reward different work: AI Overviews leans on classic ranking and snippets, AI Mode runs a deeper multi-corpus fan-out. A page can win one and lose the other, so a single score hides the gap. This scorecard splits them."),
   ("Which track should I prioritise?","Start with whichever scores lower for your category. AI Overviews rewards strong snippets and schema; AI Mode rewards entity records, comparison content and coverage across the Knowledge and Shopping graphs. The scorecard shows where you are thin.")],
  [("AI Mode vs AI Overviews","/blogs/ai-mode-vs-ai-overviews"),("Query fan-out explained","/blogs/query-fan-out-how-one-prompt-becomes-ten-searches"),("AI Platform Optimization Matrix","/tools/ai-platform-optimizer")]),
 T("engine-reddit-reliance-planner","Engine Reddit-Reliance Planner",
  ["Select the AI engines you are targeting.","See how much each leans on Reddit citations.","Split effort between forum seeding and on-site content accordingly."],
  [("How much do AI engines rely on Reddit?","It swings enormously by engine, from roughly 46.7% of cited sources on Perplexity down to about 0.1% on Gemini. Planning one Reddit strategy for all engines wastes effort; the split should match where your buyers' engines actually pull from."),
   ("Should I invest in Reddit for AI visibility?","Only in proportion to the engines your buyers use. If they lean on Perplexity or ChatGPT, Reddit is high-leverage; if they use Gemini, it barely moves the needle. The planner gives you the right forum-versus-on-site split.")],
  [("Why AI cites Reddit, G2 and analysts","/blogs/why-ai-cites-reddit-g2-analysts"),("The Reddit GEO playbook","/blogs/reddit-geo-playbook"),("Reddit Thread Citability Scorer","/tools/reddit-thread-citability-scorer")]),
 T("entity-home-generator","Entity Home JSON-LD Generator",
  meta="Build the nested @graph JSON-LD for your Entity Home, with explicit @id URIs and the reciprocal sameAs bindings most implementations miss. Copy or download.",
  steps=["Enter your organization details and profile URLs.","Generate the nested @graph with explicit @id URIs.","Copy or download and place it on your canonical entity page."],
  fqs=[("What is an Entity Home?","The single canonical page, usually your homepage or an about page, that a search engine treats as the authoritative record of your brand entity. Its JSON-LD, with a stable @id and sameAs links to Wikidata, Crunchbase and social profiles, is what resolves you as one distinct entity."),
   ("Why do @id URIs and reciprocal bindings matter?","A consistent @id across every JSON-LD block ties all your markup to one entity instead of many fragments. Reciprocal sameAs links (your page points out, the profiles point back) are what most implementations skip, and they are what makes the entity resolvable.")],
  rel=[("Becoming an entity","/blogs/becoming-an-entity"),("Schema markup for AI citations","/blogs/schema-markup-ai-citations-2026"),("Entity Readiness Scorecard","/tools/entity-readiness-scorecard")]),
 T("entity-readiness-scorecard","Entity Readiness Scorecard",
  meta="Score your entity posture across the three gates and NEEATT notability signals, and get your biggest gaps ranked in priority order.",
  steps=["Answer the checks across the three entity gates.","Read your readiness score and NEEATT notability signals.","Work the ranked gaps, corroboration first."],
  fqs=[("What decides whether AI recognises my brand as an entity?","Three gates: identity (consistent name, @id and sameAs), corroboration (independent sources like Wikidata, Crunchbase and press confirm you), and notability (enough signal to warrant a knowledge panel). The scorecard rates all three and ranks your gaps."),
   ("Do I need a Wikipedia page to be a recognised entity?","No. Wikidata, a complete Crunchbase, consistent NAP and sameAs schema can establish an entity without meeting Wikipedia notability. The scorecard flags which corroboration sources you are missing.")],
  rel=[("Entity SEO and Google Knowledge Panels","/blogs/becoming-an-entity"),("Authority seeding for AI","/blogs/authority-seeding-ai-llm-trust"),("Entity Home JSON-LD Generator","/tools/entity-home-generator")]),
 T("expected-citation-estimator","Expected-Citation Estimator",
  ["Enter your topic's facet count and how many you cover.","Set an average selection strength.","See expected citation rate and the lift from covering one more facet."],
  [("What is expected citation?","The metric that replaces rank tracking under fan-out: the average, across a topic's sub-queries, of retrieval probability (do you have a passage that can win the facet) times selection probability (does your chunk beat the others). It captures coverage, not just position."),
   ("Why does coverage beat rank here?","Because each facet is a separate contest. Ranking first on one facet buys a small edge; answering a second facet at all roughly doubles your chances of being cited. The estimator shows that covering one more facet usually outperforms polishing an existing page.")],
  [("Query fan-out explained","/blogs/query-fan-out-how-one-prompt-becomes-ten-searches"),("Citation vs Mention vs Recommendation","/blogs/citation-vs-mention-vs-recommendation"),("Facet Coverage Auditor","/tools/facet-coverage-auditor")]),
 # ---- batch 3 ----
 T("facet-coverage-auditor","Facet Coverage Auditor",
  meta="Audit your content against the eight facets a query fan-out targets, specification to edge case, and get a ranked list of the briefs you are missing.",
  steps=["Enter your topic or head term.","Mark which of the eight facets you answer in under 100 words.","Write the missing facets it ranks as briefs."],
  fqs=[("What are the eight facets of a fan-out?","Specification, compatibility, compliance, capability, price, comparison, sentiment and edge case. This frame reproduces most commercial fan-outs, so scoring your coverage against it tells you which sub-queries you can already win and which are open."),
   ("Why audit facets instead of keywords?","Because 95% of fan-out sub-queries have zero keyword volume, there is nothing to sort in a keyword tool. The metric that replaces search volume is facet coverage: how many of the sub-queries in your topic you answer better than anyone.")],
  rel=[("Query fan-out explained","/blogs/query-fan-out-how-one-prompt-becomes-ten-searches"),("Anatomy of a high-citation page","/blogs/anatomy-of-a-high-citation-page"),("Fan-Out Content Brief Generator","/tools/fan-out-content-brief-generator")]),
 T("fact-consistency-checker","Fact-Consistency Checker",
  meta="Check whether your core facts match across every profile. Drift fragments your entity, so this flags every conflict against your Entity Home.",
  steps=["Enter your canonical facts (founding date, HQ, name).","Paste the values from each external profile.","Fix every conflict the checker flags against your Entity Home."],
  fqs=[("Why does fact consistency matter for AI?","When your founding date, name or HQ differ across Crunchbase, LinkedIn and your site, engines see several weakly-linked entities instead of one strong one. Consistent facts across profiles are what let a model resolve and trust you as a single entity."),
   ("Which facts should match everywhere?","The identity-defining ones: legal and brand name, founding date, headquarters, key people and category. The checker compares each against your Entity Home and flags drift so you can reconcile the outliers.")],
  rel=[("Becoming an entity","/blogs/becoming-an-entity"),("Hallucination-proofing your brand","/blogs/hallucination-proofing-your-brand"),("Entity Home JSON-LD Generator","/tools/entity-home-generator")]),
 T("fan-out-content-brief-generator","Fan-Out Content Brief Generator",
  ["Enter your head term and an optional competitor.","Get eight question-style H2s, one per facet, with target corpora.","Copy or download the brief and write each answer first."],
  [("What does the brief generator produce?","An eight-facet content brief for one head term: a question-style H2 per facet (specification, compatibility, compliance, capability, price, comparison, sentiment, edge case) plus the corpus each sub-query targets. Ship it as a cluster, not one monster page."),
   ("Why a cluster instead of one long guide?","Five focused pages produce five audition chunks, five title tags and five shots at the fusion pool; one 6,000-word guide produces one of each. The brief splits a topic into focused pages that each win their facet.")],
  [("Query fan-out explained","/blogs/query-fan-out-how-one-prompt-becomes-ten-searches"),("The topical authority cluster","/blogs/topical-authority-cluster-ai-shortlists"),("Facet Coverage Auditor","/tools/facet-coverage-auditor")]),
 T("geo-lift-calculator","GEO Lift Calculator",
  meta="Model the AI-citation lift on your brand's Share of Model. Toggle the on-page and off-page signals from the Princeton GEO research and see the modeled outcome.",
  steps=["Set your baseline Share of Model.","Toggle the GEO signals you plan to add.","Read the modeled citation lift."],
  fqs=[("What does the GEO Lift Calculator model?","The projected lift in your Share of Model from adding specific, research-backed signals, expert quotes, statistics, cited sources and clean structure, drawn from the Princeton/KDD GEO experiment, where those interventions produced measured citation gains of roughly 28-41%."),
   ("Are the lift numbers guaranteed?","No. They are modeled from published experimental averages and are directional, not a promise for one page. Use them to prioritise which interventions to run first, then verify with your own before-and-after citation tracking.")],
  rel=[("What the GEO evidence shows","/blogs/citation-vs-mention-vs-recommendation"),("RLHF and your brand","/blogs/rlhf-and-your-brand"),("GEO Readiness Scorecard","/tools/geo-readiness-scorecard")]),
 T("geo-readiness-scorecard","GEO Readiness Scorecard",
  ["Rate your brand across crawlability, authority, Information Gain and structure.","Read your readiness score and band.","Fix the lowest-scoring dimension first."],
  [("What does the GEO Readiness Scorecard measure?","The four things that decide whether AI engines cite you: crawlability (can bots fetch and read the page), authority (do trusted sources corroborate you), Information Gain (do you add something not already everywhere), and structure (is the answer extractable). It scores each and ranks your gaps."),
   ("What is Information Gain?","The degree to which your page adds new, non-redundant information versus restating what every other page says. Engines favour sources that contribute something, original data, a distinct point of view, so high Information Gain lifts citation odds.")],
  [("GEO Audit: how to run an AI visibility audit","/blogs/geo-foundation-audit"),("Authority seeding for AI","/blogs/authority-seeding-ai-llm-trust"),("GEO Content-Mix Planner","/tools/content-mix-planner")]),
 T("llms-txt-generator","llms.txt Generator",
  ["Enter your priority pages by section.","Generate a spec-compliant llms.txt.","Copy or download and serve it at /llms.txt."],
  [("What is an llms.txt file?","A plain-text index, served at yourdomain.com/llms.txt, that points AI crawlers to the pages worth citing: a single H1, a blockquote summary and sectioned links with descriptions. It takes minutes to ship and most sites have not.") ,
   ("Does llms.txt actually help?","It is not a guaranteed ranking lever, and search crawlers largely ignore it today, but coding agents and some AI tools read it, and it is a cheap, low-risk way to steer crawlers to your best pages. Pair it with crawl access and schema.")],
  [("Does llms.txt actually do anything yet?","/blogs/does-llms-txt-do-anything-yet"),("How AI crawlers index your site","/blogs/how-ai-crawlers-index-your-site"),("llms.txt Validator","/tools/llms-txt-validator")]),
 T("llms-txt-validator","llms.txt Validator",
  ["Paste your existing llms.txt.","See it linted against the spec.","Fix the errors it flags before shipping."],
  [("What does the validator check?","Spec compliance: exactly one H1, a blockquote summary, broad section headings, the mandatory colon on each link line, and fact-rich link descriptions. It flags the small syntax mistakes that make a file unreadable to the crawlers it is meant to guide."),
   ("What is the most common llms.txt mistake?","Missing or malformed link lines, no colon after the link, or vague descriptions. The validator catches these plus multiple H1s and missing summaries, so the file parses cleanly.")],
  [("Does llms.txt actually do anything yet?","/blogs/does-llms-txt-do-anything-yet"),("Schema markup for AI citations","/blogs/schema-markup-ai-citations-2026"),("llms.txt Generator","/tools/llms-txt-generator")]),
 T("off-site-authority-scorecard","Off-Site Authority Stack Scorecard",
  ["Score your presence across review sites, analysts, Reddit and entity schema.","Read your off-site authority score and band.","Close the weakest layer first."],
  [("What is the off-site authority stack?","The third-party surfaces AI engines pull from when they cross-check you: review sites (G2, Capterra), analyst coverage, community discussion (Reddit, forums) and entity records (Wikidata). Since most citations point off your domain, this stack is where the ceiling is set."),
   ("Why does off-site authority matter more than my own site?","Because AI answers treat first-party claims with structural distrust and roughly 97% of citations point to third-party domains. A strong off-site stack is what makes engines treat your claims as corroborated and safe to cite.")],
  [("Why AI cites Reddit, G2 and analysts","/blogs/why-ai-cites-reddit-g2-analysts"),("Authority seeding for AI","/blogs/authority-seeding-ai-llm-trust"),("Engine Reddit-Reliance Planner","/tools/engine-reddit-reliance-planner")]),
 # ---- batch 4 ----
 T("page-citability-analyzer","Page Citability Analyzer",
  ["Paste a page.","See it scored against the high-citation structural fingerprint.","Apply the fixes it ranks as highest-leverage."],
  [("What makes a page citable by AI?","A consistent structural fingerprint: question-style headings, a direct answer in the first lines of each section, dense proof (statistics and named sources), and clean semantic HTML. The analyzer scores your page against that fingerprint and ranks the fixes."),
   ("How is this different from a normal SEO audit?","An SEO audit checks rankability, meta, links, speed. This checks extractability: whether a retriever can lift a self-contained answer from your page and cite it. A page can rank well and still be uncitable if its answers are buried.")],
  [("Anatomy of a high-citation page","/blogs/anatomy-of-a-high-citation-page"),("How your page gets retrieved","/blogs/how-your-page-gets-retrieved"),("Chunk Retrievability Analyzer","/tools/chunk-retrievability-analyzer")]),
 T("platform-weighted-visibility-calculator","Platform-Weighted Visibility Calculator",
  ["Enter mentions and prompts issued per engine.","Adjust the platform weights for your market.","Read the weighted score and per-engine breakdown."],
  [("Why weight visibility by platform?","Because engines do not perform uniformly, and pooling them into one average hides where you win or lose. A weighted score, normalised over the engines you actually track, reflects the engines your buyers use instead of treating all six as equal."),
   ("How many runs should I average before entering counts?","Three to five per engine. AI answers are non-deterministic, so a single run is a sample of size one. Averaging smooths the run-to-run variance before you compute a visibility score.")],
  [("Citation vs Mention vs Recommendation","/blogs/citation-vs-mention-vs-recommendation"),("Prompt-to-citation tracking","/blogs/prompt-to-citation-tracking"),("Sentiment & Share-of-Voice Calculator","/tools/sentiment-share-of-voice-calculator")]),
 T("product-offer-jsonld-generator","Product/Offer JSON-LD Generator",
  ["Enter product name, price, availability and attributes.","Generate agent-readable Product + Offer JSON-LD.","Copy or download and place it on the product page."],
  [("Why do AI shopping agents need Product JSON-LD?","Because an agent evaluates a product from structured data, not your page design. Explicit Product and Offer schema, with SKU, price, availability, live inventory and a dateModified stamp, is what lets an agent compare and transact instead of skipping you."),
   ("What fields matter most for agentic commerce?","Price and currency, availability and inventory level, SKU or GTIN, granular attributes as distinct fields, and dateModified. Stale or missing values are where agents drop a product from the consideration set.")],
  [("When the buyer is a bot","/blogs/when-the-buyer-is-a-bot"),("Schema markup for AI citations","/blogs/schema-markup-ai-citations-2026"),("Product Schema Auditor","/tools/product-schema-auditor")]),
 T("product-schema-auditor","Product Schema (JSON-LD) Auditor",
  ["Paste a product page or its JSON-LD.","See whether an agent can evaluate and transact with it.","Add the fields it flags as missing."],
  [("What does the product schema auditor check?","Whether your Product/Offer JSON-LD carries the fields an AI shopping agent needs, name, SKU or GTIN, brand, price, currency, availability, live inventory, granular attributes, image and dateModified, and scores how transactable the page is."),
   ("What happens if a field is missing?","The agent may skip your product for a competitor whose data parses cleanly. Missing price, availability or inventory are the common disqualifiers; the auditor flags each gap so you can close it.")],
  [("When the buyer is a bot","/blogs/when-the-buyer-is-a-bot"),("Agentic Commerce Readiness Scorecard","/tools/agentic-commerce-readiness-scorecard"),("Product/Offer JSON-LD Generator","/tools/product-offer-jsonld-generator")]),
 T("query-fan-out-simulator","Query Fan-Out Simulator",
  ["Type a buyer query.","Watch it decompose into parallel sub-queries by dimension.","Map each sub-query to the content that resolves it."],
  [("What does the fan-out simulator show?","How a real engine shreds one buyer query into parallel sub-queries, one per dimension (spec, price, compliance, comparison, sentiment), and which content type resolves each branch. It makes the hidden searches you are actually competing on visible."),
   ("How is this an illustrative tool?","It models the decomposition pattern documented for AI Mode and similar engines; the exact sub-queries a live engine writes vary by context. Use it to plan coverage across dimensions, not as a literal transcript of one engine's run.")],
  [("Query fan-out explained","/blogs/query-fan-out-how-one-prompt-becomes-ten-searches"),("AI Mode vs AI Overviews","/blogs/ai-mode-vs-ai-overviews"),("Facet Coverage Auditor","/tools/facet-coverage-auditor")]),
 T("reddit-thread-citability-scorer","Reddit Thread Citability Scorer",
  meta="AI engines cite Reddit threads on structure, not karma. Score a thread against the cited-thread signature and get the highest-leverage fixes.",
  steps=["Paste or describe the thread.","Score it against the cited-thread signature.","Apply the highest-leverage structural fixes."],
  fqs=[("Why do AI engines cite low-upvote Reddit threads?","Because they select on structure, not popularity, most cited B2B threads have fewer than 20 upvotes. A clear question, a direct detailed answer, named tools and a recommendation pattern matter far more than karma."),
   ("What makes a Reddit thread citable?","A specific question in the title, a substantive top answer that names products with reasons, comparison language ('X vs Y'), and recent activity. The scorer rates a thread against that signature and shows what to improve.")],
  rel=[("The Reddit GEO playbook","/blogs/reddit-geo-playbook"),("Why AI cites Reddit, G2 and analysts","/blogs/why-ai-cites-reddit-g2-analysts"),("Reddit Warm-Up & Compliance Planner","/tools/reddit-warmup-compliance-planner")]),
 T("reddit-warmup-compliance-planner","Reddit Warm-Up & Compliance Planner",
  meta="Reddit shadowbans accounts that promote too early. Enter your account age, karma and activity to get your phase, link gate and safe posting ratio.",
  steps=["Enter your account age, karma and activity.","Read your warm-up phase and link gate.","Follow the safe self-promotion ratio."],
  fqs=[("Why do Reddit accounts get shadowbanned?","Because they promote before earning standing, links too early, a thin history, a high self-promotion ratio. Reddit's filters and moderators penalise that, and a shadowbanned account's content never reaches the threads AI cites."),
   ("What is a safe self-promotion ratio on Reddit?","The common guidance is roughly nine genuine contributions for every one that links your own content. The planner sets the ratio and the link gate against your account's age and karma so you build standing before you post.")],
  rel=[("The Reddit GEO playbook","/blogs/reddit-geo-playbook"),("Engine Reddit-Reliance Planner","/tools/engine-reddit-reliance-planner"),("Reddit Thread Citability Scorer","/tools/reddit-thread-citability-scorer")]),
 T("retrieval-readiness-checklist","Retrieval-Readiness Checklist",
  ["Score a page against the eight pre-publish checks.","Read the readiness score and ranked gaps.","Fix the gaps before you publish."],
  [("What is on the retrieval-readiness checklist?","Eight pre-publish checks for surviving chunking and reranking: self-contained answers, question headings, monosemantic passages, plain-HTML facts, schema, named sources, freshness and internal linking. It scores a page and ranks the gaps before you ship."),
   ("When should I run this checklist?","Before publishing, and again after major edits. Fixing retrieval gaps pre-publish is far cheaper than diagnosing why a live page never gets cited, most misses come from a handful of these eight items.")],
  [("How your page gets retrieved","/blogs/how-your-page-gets-retrieved"),("Query fan-out explained","/blogs/query-fan-out-how-one-prompt-becomes-ten-searches"),("Page Citability Analyzer","/tools/page-citability-analyzer")]),
 # ---- batch 5 ----
 T("robots-txt-ai-generator","robots.txt for AI Generator",
  ["Toggle allow or disallow per AI crawler.","Separate citation bots from training bots.","Copy the generated robots.txt to your site root."],
  [("Can I allow AI citation bots but block training bots?","Yes, and you should decide deliberately. Citation crawlers (OAI-SearchBot, PerplexityBot, Google-Extended for AI surfaces) are the ones that quote you; training crawlers (GPTBot, CCBot) feed model training. This generator lets you allow one class and control the other."),
   ("Will blocking GPTBot stop me being cited?","It can. Some crawlers serve both training and retrieval, and over-blocking removes you from the pool that quotes you. The generator flags which bots affect citations so you do not block the ones you want.")],
  [("How AI crawlers index your site","/blogs/how-ai-crawlers-index-your-site"),("Does llms.txt actually do anything yet?","/blogs/does-llms-txt-do-anything-yet"),("AI Bot Log Analyzer","/tools/ai-bot-log-analyzer")]),
 T("rrf-rank-fusion-calculator","RRF Rank-Fusion Calculator",
  ["Enter a dense ranking and a keyword ranking.","See them merged with Reciprocal Rank Fusion (k=60).","Read why good-on-both beats best-on-one."],
  [("What is Reciprocal Rank Fusion?","The algorithm engines use to merge several ranked lists into one. Each document scores the sum, across every list it appears in, of one over a constant (k=60) plus its rank. It structurally rewards documents that appear across multiple lists over one that tops a single list."),
   ("Why is ranking #1 overrated under RRF?","Because with k=60, rank 1 contributes 0.01639 and rank 10 contributes 0.01429, a 13% gap. Appearing at all in a second list is worth close to 100%. Coverage across sub-queries beats depth on one.")],
  [("Query fan-out explained","/blogs/query-fan-out-how-one-prompt-becomes-ten-searches"),("Internal linking for AI retrieval","/blogs/internal-linking-for-ai-retrieval"),("Chunk Retrievability Analyzer","/tools/chunk-retrievability-analyzer")]),
 T("saas-funnel-gap-analyzer","B2B SaaS Funnel Gap Analyzer",
  ["Enter how many pages you have per funnel stage.","See your funnel balance versus where AI sends buyers.","Build where the gap is widest."],
  [("What is an inverted content funnel?","When a program over-produces top-of-funnel awareness content and under-produces the bottom-of-funnel comparison and buyer pages AI engines actually cite for purchase-intent queries. The analyzer shows your balance and where the gap sits."),
   ("Where should B2B SaaS add content first?","Usually the middle and bottom: comparison pages, alternatives pages and buyer guides. Those are the formats AI engines quote for high-intent prompts, and most programs are thin there while heavy on blog awareness posts.")],
  [("Getting found on Google and AI","/blogs/payments-getting-found-google-ai"),("The topical authority cluster","/blogs/topical-authority-cluster-ai-shortlists"),("GEO Content-Mix Planner","/tools/content-mix-planner")]),
 T("sentiment-share-of-voice-calculator","Sentiment & Share-of-Voice Calculator",
  ["Enter positive, neutral and negative mention counts.","Add your brand and verified competitor mentions.","Read the sentiment index and share of voice."],
  [("How is the sentiment index calculated?","On a 0 to 100 scale where positive mentions count full, neutral count half and negative count zero. All-positive scores 100, all-neutral 50, all-negative 0. A negative mention costs exactly twice what a neutral one does."),
   ("Why exclude hallucinated competitors from share of voice?","Because engines invent plausible vendor names, and a fake competitor in the denominator quietly depresses your score. Resolve every competitor to a real domain before counting it, the calculator keeps the denominator honest.")],
  [("Citation vs Mention vs Recommendation","/blogs/citation-vs-mention-vs-recommendation"),("Why engines recommend different vendors","/blogs/why-engines-recommend-different-vendors"),("Platform-Weighted Visibility Calculator","/tools/platform-weighted-visibility-calculator")]),
 T("ugc-prompt-injection-scanner","UGC Prompt-Injection Scanner",
  ["Paste a review or user-generated text.","See flagged injection patterns, hidden comments and obfuscated URLs.","Sanitise the content before it renders on your page."],
  [("What is prompt injection in user content?","Instruction-shaped text hidden in reviews or comments, HTML comments, 'ignore previous instructions', redirect payloads, that tries to hijack an AI agent parsing your page. Rendered on a public product page, it becomes an executable attack surface."),
   ("How do I protect against it?","Sanitise user-generated content at ingestion: strip HTML comments and control sequences, and flag instruction-shaped patterns before storage. The scanner shows which reviews are clean, suspicious or malicious.")],
  [("When the buyer is a bot","/blogs/when-the-buyer-is-a-bot"),("Hallucination-proofing your brand","/blogs/hallucination-proofing-your-brand"),("Product Schema Auditor","/tools/product-schema-auditor")]),
 T("zero-click-traffic-risk","Zero-Click Traffic-at-Risk Estimator",
  meta="As AI Overviews and AI Mode expand, more searches resolve without a click. Estimate how much of your organic traffic sits in the zero-click blast radius.",
  steps=["Enter your organic traffic and query mix.","See how much sits in the zero-click blast radius.","Shift the at-risk share toward AI-citation and buyer intent."],
  fqs=[("What is zero-click risk?","The share of your organic traffic likely to disappear as AI Overviews and AI Mode answer queries directly on the results page. Informational and definitional queries are most exposed; the estimator sizes your blast radius."),
   ("How do I reduce zero-click exposure?","Shift toward queries that still earn a click, comparison, pricing and buyer-intent terms, and toward being the cited source inside AI answers so you capture referral traffic even when the click moves. The estimator shows how much traffic to reposition.")],
  rel=[("Winning Google isn't winning AI","/blogs/winning-google-isnt-winning-ai"),("Why traditional SEO is no longer enough","/blogs/why-traditional-seo-is-no-longer-enough"),("B2B SaaS Funnel Gap Analyzer","/tools/saas-funnel-gap-analyzer")]),
]

if __name__=="__main__":
    for t in REST:
        enhance(**t); print("enhanced",t["slug"])
